### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by md84419** [ThinkDigitalSoftware/conditional_wrapper#1]
The library 'package:conditional_wrapper/conditional_wrapper.dart' is legacy, and should not be imported into a null safe library.
Try migrating the imported library.

Error: This project cannot run with sound null safety, because one or more project dependencies do not
support null safety:

- package:conditional_wrapper

dependencies:
conditional_wrapper: ^1.0.1

**Comment by ThinkDigitalSoftware** [comment]
Ah, yes. Thanks for reporting this. I haven't upgraded my packages yet. I can take a look at this in the morning

**Comment by mzdm** [comment]
I can submit a PR for null safety support if you want @ThinkDigitalSoftware

**Comment by ThinkDigitalSoftware** [comment]
That would be great! Thank you

**Comment by mzdm** [comment]
> That would be great! Thank you

I submitted #2, would you please take a look? Thanks!
